version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

formats:
  - pdf
  - epub

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
  system_packages: true  